### ISSUE TITLE
Insisting on users to upgrade to Windows 7

### ISSUE THREAD

**Issue by Recharged** [pwnsdx/Tox-Website#18]
I went to check out the new website with an agent-spoofer, and I assume I spoofed as an older version of a Windows web browser. Once I got to the website, you insisted on me to upgrade to Windows 7.

This may very well not be an issue; however, I believe it's unethical. The more proper way would be to inform the user that they're running an older version which you don't support or to insist on the user to upgrade to a free operating system, such as GNU/Linux.
![selection_039](https://cloud.githubusercontent.com/assets/8312814/6772232/139f6b90-d0c7-11e4-8fd2-7eefbbc9b4ad.jpg)

**Comment by urras** [comment]
I fail to see the difference between Asking them to upgrade to Windows 7=< and telling them that they're running an older version that we don't support. However, I could be missing the point entirely. Care to provide some insight?

**Comment by Recharged** [comment]
Well, asking a user to upgrade to a nonfree operating system is entirely different than just informing them that theirs is out-of-date.

Basically, it's like asking a user to throw a new pair of handcuffs on themselves. That's how I see it, at least.

**Comment by stqism** [comment]
@Recharged Our goal with Tox isn't to promote any particular political agendas, beliefs, or operating system choices.

Users are free to use whatever they feel like and are most comfortable with and it isn't our place to tell them otherwise. Using out of date versions of operating systems is something we should encourage people don't do though, it takes a lot more work making sure things and features support older versions and sometimes times they lose features or we have to make compromises and not support versions.

**Comment by Recharged** [comment]
I assumed that wasn't the purpose; however, it felt wrong to ask a user to switch to a newer version of Windows.

Yes, I do agree with that very much. I just felt like stating something more along the lines of "Please upgrade to a supported operating system," then linking the user to a list of supported operating systems would look better and not seem like Tox requires Windows 7 or later.

**Comment by pwnsdx** [comment]
Yesterday I installed Ubuntu on the PC of my brother and he definitely want to return to Windows 8 because he want is old habits back (Ubuntu have a lots of bugs/crash, too). It is very difficult to move someone to an new operating system. Especially when those people don't know how to use the terminal. So this is not possible to ask to upgrade to GNU/Linux because the user use Windows Vista. The user could think that there is absolutely no Windows version and this will result in a misunderstanding. That's why it's better to write "Your version of Windows is outdated, please use a new one."

**Comment by Recharged** [comment]
I'm not saying it's difficult for a newbie to get into GNU/Linux (however, choosing Ubuntu as your brother's first distribution is a poor choice -- you should have chosen something more similar to Windows, perhaps Xubuntu). And aside from that, the terminal isn't something you absolutely have to use.

However, I never once stated that it should tell the user to upgrade to GNU/Linux -- it should state only that your operating system is not supported and that the user should upgrade to a supported operating system (whether that be Windows, GNU/Linux, or even FreeBSD is up to the user).

Hence is why I stated it should link to a list of supported operating systems. All it must say is, "Your operating system is unsupported by Tox; please upgrade to a supported operating system" then it lead to the list of supported operating systems (Windows included, as it is one of Tox's supported operating system).
The user can then either install one of the minimum required operating systems for use of Tox or not.
